#!/bin/bash

echo "Checking Terraform formatting in infra folder..."
terraform fmt -check -recursive ./infra

echo "Checking Terraform formatting in main folder..."
terraform fmt -check -recursive ./main

echo "Pre-commit checks passed successfully."
exit 0
